2022-01-16 18:41:49   Arguments: Namespace(upscale_input=False, downscale_input=False, augment_input='None', backbone='resnet50moco', use_netvlad=True, netvlad_clusters=64, use_gem=None, gem_p=3, gem_eps=1e-06, use_sgd=None, use_adagrad=None, momentum=0.9, train_batch_size=4, infer_batch_size=16, margin=0.1, epochs_num=20, patience=3, lr=1e-05, cache_refresh_rate=1000, queries_per_epoch=5000, negs_num_per_query=10, neg_samples_num=1000, seed=0, device='cuda', num_workers=12, val_positive_dist_threshold=25, train_positives_dist_threshold=10, recall_values=[1, 5, 10, 20], datasets_folder='./Dataset_pitts30k', exp_name='default', test_dataset_name=None, test_model_path=None, output_folder='runs/default/2022-01-16_18-41-49')
2022-01-16 18:41:49   The outputs are being saved in runs/default/2022-01-16_18-41-49
2022-01-16 18:41:49   Using 1 GPUs and 12 CPUs
2022-01-16 18:41:49   There are 96 queries without any positives within the training set. They won't be considered as they're useless for training.
2022-01-16 18:41:49   Train query set: < TripletsDataset, pitts30k - #database: 10000; #queries: 7320 >
2022-01-16 18:41:49   Val set: < BaseDataset, pitts30k - #database: 10000; #queries: 7608 >
2022-01-16 18:41:49   Test set: < BaseDataset, pitts30k - #database: 10000; #queries: 6816 >
2022-01-16 18:41:49   
Traceback (most recent call last):
  File "/home/franzhd/Aml_project/project_vg/run_train.py", line 47, in <module>
    model = network.GeoLocalizationNet(args)
  File "/home/franzhd/Aml_project/project_vg/network.py", line 20, in __init__
    self.backbone = get_backbone(args)
  File "/home/franzhd/Aml_project/project_vg/network.py", line 81, in get_backbone
    backbone = torch.load('moco_v1_200ep_pretrain.pth.tar')
  File "/home/franzhd/.local/lib/python3.9/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/franzhd/.local/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/franzhd/.local/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'moco_v1_200ep_pretrain.pth.tar'

