2022-01-06 13:25:12   Arguments: Namespace(use_netvlad=None, netvlad_clusters=64, train_batch_size=4, infer_batch_size=16, margin=0.1, epochs_num=10, patience=3, lr=1e-05, cache_refresh_rate=1000, queries_per_epoch=5000, negs_num_per_query=10, neg_samples_num=1000, seed=0, device='cuda', num_workers=8, val_positive_dist_threshold=25, train_positives_dist_threshold=10, recall_values=[1, 5, 10, 20], datasets_folder='./Data', exp_name='default', output_folder='runs/default/2022-01-06_13-25-12')
2022-01-06 13:25:12   The outputs are being saved in runs/default/2022-01-06_13-25-12
2022-01-06 13:25:12   Using 1 GPUs and 12 CPUs
2022-01-06 13:25:12   Loading dataset Pitts30k from folder ./Data
2022-01-06 13:25:12   There are 96 queries without any positives within the training set. They won't be considered as they're useless for training.
2022-01-06 13:25:12   Train query set: < TripletsDataset, pitts30k - #database: 10000; #queries: 7320 >
2022-01-06 13:25:12   Val set: < BaseDataset, pitts30k - #database: 10000; #queries: 7608 >
2022-01-06 13:25:12   Test set: < BaseDataset, pitts30k - #database: 10000; #queries: 6816 >
2022-01-06 13:25:12   Train only conv4 of the ResNet-18 (remove conv5), freeze the previous ones
2022-01-06 13:25:17   Output dimension of the model is 16384
2022-01-06 13:25:17   Start training epoch: 00
2022-01-06 13:25:17   Cache: 0 / 5
2022-01-06 13:25:18   
Traceback (most recent call last):
  File "/home/franzhd/Aml_project/project_vg/train.py", line 70, in <module>
    triplets_ds.compute_triplets(args, model)
  File "/home/franzhd/Aml_project/project_vg/datasets_ws.py", line 206, in compute_triplets
    cache = self.compute_cache(args, model, subset_ds, (len(self), args.features_dim))
  File "/home/franzhd/Aml_project/project_vg/datasets_ws.py", line 167, in compute_cache
    cache[indexes.numpy()] = features.cpu().numpy()
ValueError: shape mismatch: value array of shape (16,256) could not be broadcast to indexing result of shape (16,16384)

